In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

coal_percentages = np.array([
    [26, 20, 39, 0, 15, 0, 0,0,0,0,0,0,0],
    [26, 20, 39, 0, 15, 0, 0,0,0,0,0,0,0],
    [26, 20, 39, 0, 15, 0, 0,0,0,0,0,0,0],
    [26, 20, 39, 0, 15, 0, 0,0,0,0,0,0,0],
    [22, 17, 30, 0, 16, 15, 0,0,0,0,0,0,0],
    [22, 17, 30, 0, 16, 15, 0,0,0,0,0,0,0],
    [22, 17, 30, 0, 16, 15, 0,0,0,0,0,0,0],
    [22, 17, 30, 0, 16, 15, 0,0,0,0,0,0,0],
    [22, 17, 30, 0, 16, 15, 0,0,0,0,0,0,0],
    [24, 20, 32, 0, 16, 8, 0,0,0,0,0,0,0],
    [24, 20, 32, 0, 16, 8, 0,0,0,0,0,0,0],
    [24, 20, 32, 0, 16, 8, 0,0,0,0,0,0,0],
    [24, 20, 32, 0, 16, 8, 0,0,0,0,0,0,0],
    [24, 20, 32, 0, 16, 8, 0,0,0,0,0,0,0],
    [22, 26, 32, 0, 20, 0, 0,0,0,0,0,0,0],
    [16, 18, 34, 14, 18, 0, 0,0,0,0,0,0,0],
    [16, 18, 34, 14, 18, 0, 0,0,0,0,0,0,0],
    [16, 18, 34, 14, 18, 0, 0,0,0,0,0,0,0],
    [22, 20, 38, 0, 20, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [17, 17, 38, 14, 14, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 19, 36, 19, 8, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [18, 25, 42, 0, 15, 0, 0,0,0,0,0,0,0],
    [22, 22, 35, 0, 16, 0, 5,0,0,0,0,0,0],
    [22, 22, 35, 0, 16, 0, 5,0,0,0,0,0,0],
    [22, 22, 35, 0, 16, 0, 5,0,0,0,0,0,0],
    [22, 22, 35, 0, 16, 0, 5,0,0,0,0,0,0],
    [22, 22, 35, 0, 16, 0, 5,0,0,0,0,0,0],
    [22, 22, 35, 0, 16, 0, 5,0,0,0,0,0,0]
])

result = np.array([
    [16.00, 0.93, 4.17, 0.78, 1.56, 18.64, 33.00, 24.25, 6.93, 92.47, 6.20, 4.33, 67.10, 25.10],
    [15.52, 0.85, 4.60, 0.78, 1.71, 19.08, 34.57, 22.63, 6.50, 92.47, 6.13, 4.40, 67.40, 23.90],
    [16.18, 0.90, 4.63, 0.78, 1.74, 19.37, 33.23, 22.70, 6.37, 92.33, 6.27, 4.40, 67.80, 24.00],
    [16.02, 0.97, 3.77, 0.78, 1.59, 18.95, 33.21, 22.98, 6.67, 92.40, 6.27, 4.33, 67.50, 24.10],
    [15.77, 0.90, 4.37, 0.78, 1.76, 18.41, 33.91, 23.94, 6.63, 92.96, 6.22, 3.82, 67.20, 23.40],
    [15.48, 0.97, 4.20, 0.78, 1.62, 18.86, 34.32, 23.31, 6.60, 92.74, 5.73, 4.53, 68.80, 22.00],
    [15.40, 0.90, 4.20, 0.78, 1.37, 18.99, 33.76, 24.48, 6.43, 92.60, 6.13, 4.27, 68.50, 23.30],
    [15.13, 0.92, 4.17, 0.78, 1.31, 19.58, 33.30, 25.10, 6.03, 92.80, 6.13, 4.07, 68.70, 22.10],
    [15.13, 0.95, 4.20, 0.78, 1.44, 19.49, 33.14, 24.37, 6.53, 92.87, 6.13, 4.00, 68.90, 23.10],
    [15.25, 0.88, 4.00, 0.71, 1.59, 19.33, 32.89, 23.62, 6.37, 92.67, 6.95, 4.38, 68.40, 22.60],
    [15.70, 0.97, 4.10, 0.78, 1.61, 16.47, 36.76, 25.95, 6.47, 92.60, 6.20, 4.20, 67.80, 24.00],
    [15.20, 0.90, 4.07, 0.78, 0.99, 17.94, 34.52, 24.72, 6.40, 92.67, 6.13, 4.20, 65.60, 23.40],
    [15.10, 0.90, 4.40, 0.78, 1.59, 18.96, 33.30, 23.35, 6.60, 93.00, 6.20, 3.80, 0.78, 0.78],
    [14.75, 0.83, 3.90, 0.78, 1.12, 17.56, 35.63, 24.15, 6.35, 92.50, 6.10, 4.40, 68.30, 23.00],
    [15.33, 0.93, 4.20, 0.78, 1.88, 18.48, 33.05, 24.82, 6.40, 92.53, 6.93, 4.53, 69.03, 22.39],
    [16.03, 0.95, 3.84, 1.00, 1.72, 18.90, 33.78, 23.07, 6.70, 92.50, 6.00, 4.50, 67.89, 25.14],
    [15.73, 0.98, 4.03, 0.78, 1.57, 20.23, 32.53, 23.42, 6.43, 92.80, 6.20, 4.00, 69.88, 22.44],
    [15.07, 0.90, 4.85, 0.78, 1.41, 19.46, 32.60, 23.80, 6.70, 92.40, 6.00, 4.60, 67.10, 23.60],
    [15.00, 1.00, 4.43, 1.20, 2.08, 18.29, 33.53, 24.30, 6.03, 92.60, 6.07, 4.33, 68.05, 24.06],
    [15.35, 0.88, 3.80, 0.85, 1.70, 17.97, 33.86, 24.66, 6.50, 92.07, 6.33, 4.60, 68.10, 24.43],
    [14.95, 0.98, 3.80, 0.91, 1.70, 19.02, 34.25, 23.17, 5.87, 92.80, 6.87, 4.33, 68.73, 24.22],
    [15.45, 1.00, 3.77, 1.39, 1.68, 19.65, 31.61, 24.28, 6.77, 92.60, 6.13, 4.27, 69.70, 23.30],
    [15.10, 1.04, 3.57, 0.88, 1.66, 18.54, 34.18, 23.76, 5.97, 92.67, 6.00, 4.33, 68.70, 23.60],
    [15.22, 1.00, 3.77, 0.78, 1.57, 18.64, 33.21, 24.00, 6.00, 92.60, 6.00, 4.40, 69.20, 23.80],
    [15.15, 1.08, 3.57, 0.78, 1.83, 19.42, 32.12, 23.92, 6.53, 92.60, 6.13, 4.27, 68.90, 23.40],
    [15.25, 0.97, 3.80, 0.78, 1.73, 19.19, 32.63, 23.52, 6.67, 92.47, 6.13, 4.40, 66.10, 26.50],
    [14.92, 1.08, 3.60, 0.78, 1.62, 18.91, 32.97, 24.27, 6.80, 92.40, 6.13, 4.47, 67.30, 24.30],
    [14.88, 0.98, 3.87, 0.78, 1.49, 18.71, 32.70, 23.71, 6.43, 92.47, 6.13, 4.40, 67.00, 23.00],
    [15.48, 0.97, 4.20, 0.78, 1.62, 18.86, 34.32, 23.31, 6.60, 92.74, 5.73, 4.53, 68.80, 22.00],
    [15.40, 0.90, 4.20, 0.78, 1.37, 18.99, 33.76, 24.48, 6.43, 92.60, 6.13, 4.27, 68.50, 23.30],
    [15.13, 0.92, 4.17, 0.78, 1.31, 19.58, 33.30, 25.10, 6.03, 92.80, 6.13, 4.07, 68.70, 22.10],
    [15.13, 0.95, 4.20, 0.78, 1.44, 19.49, 33.14, 24.37, 6.53, 92.87, 6.13, 4.00, 68.90, 23.10],
    [15.25, 0.88, 4.00, 0.71, 1.59, 19.33, 32.89, 23.62, 6.37, 92.67, 5.95, 4.38, 68.40, 22.60],
    [15.70, 0.97, 4.10, 0.78, 1.61, 16.47, 36.76, 25.95, 6.47, 92.60, 6.20, 4.20, 67.80, 24.00],
    [15.20, 0.90, 4.07, 0.78, 0.99, 17.94, 34.52, 24.72, 6.40, 92.67, 6.13, 4.20, 65.60, 23.40],
    [15.10, 0.90, 4.40, 0.78, 1.59, 18.96, 33.30, 23.35, 6.60, 93.00, 6.20, 3.80, 68.50, 23.30],
    [14.75, 0.83, 3.90, 0.78, 1.12, 17.56, 35.63, 24.15, 6.35, 92.50, 6.10, 4.40, 68.30, 23.00],
    [15.33, 0.93, 4.20, 0.78, 1.88, 18.48, 33.05, 24.82, 6.40, 92.53, 5.93, 4.53, 69.03, 22.39],
    [16.03, 0.95, 3.84, 1.00, 1.72, 18.90, 33.78, 23.07, 6.70, 92.50, 6.00, 4.50, 67.89, 25.14],
    [15.73, 0.98, 4.03, 0.78, 1.57, 20.23, 32.53, 23.42, 6.43, 92.80, 6.20, 4.00, 69.88, 22.44],
    [15.07, 0.90, 4.85, 0.78, 1.41, 19.46, 32.60, 23.80, 6.70, 92.40, 6.00, 4.60, 67.10, 23.60],
    [15.00, 1.00, 4.43, 1.20, 2.08, 18.29, 33.53, 24.30, 6.03, 92.60, 6.07, 4.33, 68.05, 24.06],
    [15.35, 0.88, 3.80, 0.85, 1.70, 17.97, 33.86, 24.66, 6.50, 92.07, 6.33, 4.60, 68.10, 24.43],
    [14.95, 0.98, 3.80, 0.91, 1.70, 19.02, 34.25, 23.17, 5.87, 92.80, 5.87, 4.33, 68.73, 24.22],
    [15.45, 1.00, 3.77, 1.39, 1.68, 19.65, 31.61, 24.28, 6.77, 92.60, 6.13, 4.27, 69.70, 23.30],
    [15.10, 1.04, 3.57, 0.88, 1.66, 18.54, 34.18, 23.76, 5.97, 92.67, 6.00, 4.33, 68.70, 23.60],
    [15.22, 1.00, 3.77, 0.78, 1.57, 18.64, 33.21, 24.00, 6.00, 92.60, 6.00, 4.40, 69.20, 23.80],
    [15.15, 1.08, 3.57, 0.78, 1.83, 19.42, 32.12, 23.92, 6.53, 92.60, 6.13, 4.27, 68.90, 23.40],
    [15.25, 0.97, 3.80, 0.78, 1.73, 19.19, 32.63, 23.52, 6.67, 92.47, 6.13, 4.40, 66.10, 26.50],
    [14.92, 1.08, 3.60, 0.78, 1.62, 18.91, 32.97, 24.27, 6.80, 92.40, 6.13, 4.47, 67.30, 24.30],
    [14.88, 0.98, 3.87, 0.78, 1.49, 18.71, 32.70, 23.71, 6.43, 92.47, 6.13, 4.40, 67.00, 23.00],
    [14.65, 0.95, 3.77, 0.78, 1.62, 19.29, 32.63, 24.13, 6.27, 92.67, 6.13, 4.20, 65.93, 23.42]

])

X_train, X_test, y_train, y_test = train_test_split(coal_percentages, result, test_size=0.2, random_state=42)


scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)
result.shape


(52, 14)

In [2]:
from sklearn.ensemble import RandomForestRegressor

rf_model = RandomForestRegressor(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)
y_pred = rf_model.predict(X_test)

from sklearn.metrics import mean_squared_error
mse = mean_squared_error(y_test, y_pred)
print(f"Mean Squared Error: {mse}")


Mean Squared Error: 32.37953556126765


In [3]:
min_percentages = np.array([25, 25, 10, 10, 10, 0, 0, 0, 0, 0, 0, 0, 0])
max_percentages = np.array([45, 65, 25, 20, 20, 5, 4, 0, 0, 0, 0, 0, 0])
def generate_combinations(index,current_combination, current_sum):
    target_sum = 100
    if index == len(min_percentages) - 1:
        remaining = target_sum - current_sum
        if min_percentages[index] <= remaining <= max_percentages[index]:
            yield current_combination + [remaining]
        return
    for value in range(min_percentages[index], max_percentages[index] + 1):
        if current_sum + value <= target_sum:
            yield from generate_combinations(index + 1, current_combination + [value], current_sum + value)

In [4]:
all_combinations = np.array(list(generate_combinations(0, [], 0)))
print("Number of valid combinations:", len(all_combinations))
print(all_combinations[:-1000])
print(all_combinations[0])

Number of valid combinations: 132579
[[25 25 10 ...  0  0  0]
 [25 25 10 ...  0  0  0]
 [25 25 10 ...  0  0  0]
 ...
 [38 28 11 ...  0  0  0]
 [38 28 11 ...  0  0  0]
 [38 28 11 ...  0  0  0]]
[25 25 10 11 20  5  4  0  0  0  0  0  0]


# Blended Coal Calculation

In [30]:
#Blended coal array is made here
blended_coal_properties = [[0,0]] * len(all_combinations)
len(blended_coal_properties)

132579

In [5]:
x_scaled = scaler.transform(all_combinations)
predictions = rf_model.predict(x_scaled)
print(predictions)

[[15.48312069  0.94561219  4.04161287 ...  4.22143969 68.46619464
  23.35850598]
 [15.48312069  0.94561219  4.04161287 ...  4.22143969 68.46619464
  23.35850598]
 [15.48312069  0.94561219  4.04161287 ...  4.22143969 68.46619464
  23.35850598]
 ...
 [15.48312069  0.94561219  4.04161287 ...  4.22143969 68.46619464
  23.35850598]
 [15.48312069  0.94561219  4.04161287 ...  4.22143969 68.46619464
  23.35850598]
 [15.48312069  0.94561219  4.04161287 ...  4.22143969 68.46619464
  23.35850598]]


In [6]:
predictions[0]

array([15.48312069,  0.94561219,  4.04161287,  0.82918282,  1.52002634,
       19.05713319, 33.58277437, 24.00576627,  6.45681289, 92.67922727,
        6.13754018,  4.22143969, 68.46619464, 23.35850598])

# Getting and storing the input 

In [7]:
#Get all weightages for coke properties
ash_weightage = 1
vm_weightage = 1 #i think not needed 
m40_weightage = 1
m10_weightage = 1
csn_weightage = 1
cri_weightage = 1

#Get all min-max ranges for coke properties
ash_min = 0
ash_max = 100
vm_min = 0
vm_max = 100
m40_min = 0
m40_max = 100
m10_min = 0
m10_max = 100
csn_min = 0
csn_max = 100
cri_min = 0
cri_max = 100

#desired coke parameters
desired_ash = 15.4 #less
desired_VM = 0.9   #less
desired_m40 = 92   #higher
desired_m10 = 3.2   #less
desired_csr = 65   #higher
desired_cri = 23  #less
desired_coke_parameters = [desired_ash,desired_VM,4,0.8,1.54,19,33,24,6,desired_m40,desired_m10,4,desired_csr,desired_cri]

# Making sure the predictions are within min-max range

In [12]:
# Checking each prediction and adjusting if necessary #change this 
#for i, prediction in enumerate(predictions):
    # Ensure values are within the specified range
    #prediction[0] = np.clip(prediction[0], ash_min, ash_max)  # ASH
    #prediction[1] = np.clip(prediction[1], vm_min, vm_max)    # VM
    #prediction[9] = np.clip(prediction[9], m40_min, m40_max)  # M_40
    #prediction[10] = np.clip(prediction[10], m10_min, m10_max)  # M_10
    #prediction[12] = np.clip(prediction[12], csn_min, csn_max)  # CSR
    #prediction[13] = np.clip(prediction[13], cri_min, cri_max)  # CRI

In [42]:
# Corrected function to filter predictions and combinations along with blended coal properties
def filter_valid_and_invalid(predictions, combinations, blended_coal_properties):
    valid_indices = []
    invalid_indices = []
    for i, prediction in enumerate(predictions):
        # Check if all values are within the specified range
        if (
            ash_min <= prediction[0] <= ash_max and  # ASH
            vm_min <= prediction[1] <= vm_max and  # VM
            m40_min <= prediction[9] <= m40_max and  # M_40
            m10_min <= prediction[10] <= m10_max and  # M_10
            csn_min <= prediction[12] <= csn_max and  # CSR
            cri_min <= prediction[13] <= cri_max  # CRI
        ):
            valid_indices.append(i)
        else:
            invalid_indices.append(i)
    # Separate valid and invalid predictions, combinations, and blended coal properties
    valid_predictions = predictions[valid_indices]
    valid_combinations = combinations[valid_indices]
    valid_blended_coal_properties = [blended_coal_properties[i] for i in valid_indices]
    invalid_predictions = predictions[invalid_indices]
    invalid_combinations = combinations[invalid_indices]
    invalid_blended_coal_properties = [blended_coal_properties[i] for i in invalid_indices]

    return (
        valid_predictions,
        valid_combinations,
        valid_blended_coal_properties,
        invalid_predictions,
        invalid_combinations,
        invalid_blended_coal_properties,
    )

# Example blended coal properties array (redefine as needed)
blended_coal_properties = [[0, 0]] * len(all_combinations)

# Filtering valid and invalid predictions, combinations, and blended coal properties
(
    valid_predictions,
    valid_combinations,
    valid_blended_coal_properties,
    invalid_predictions,
    invalid_combinations,
    invalid_blended_coal_properties,
) = filter_valid_and_invalid(predictions, all_combinations, blended_coal_properties)

# Printing the count of valid and invalid entries
print(f"Number of valid predictions: {len(valid_predictions)}")
print(f"Number of valid combinations: {len(valid_combinations)}")
print(f"Number of valid blended coal properties: {len(valid_blended_coal_properties)}")
print(f"Number of invalid predictions: {len(invalid_predictions)}")
print(f"Number of invalid combinations: {len(invalid_combinations)}")
print(f"Number of invalid blended coal properties: {len(invalid_blended_coal_properties)}")

# Optionally display the first few valid and invalid entries
#print("First few valid blended coal properties:", valid_blended_coal_properties[:5])
#print("First few invalid blended coal properties:", invalid_blended_coal_properties[:5])

predictions = valid_predictions
all_combinations = valid_combinations
blended_coal_properties = valid_blended_coal_properties

Number of valid predictions: 132579
Number of valid combinations: 132579
Number of valid blended coal properties: 132579
Number of invalid predictions: 0
Number of invalid combinations: 0
Number of invalid blended coal properties: 0


# Running the values to get top predictions

In [43]:
# Initialize an array to store differences
differences = []
prediction = valid_predictions
all_combinations = valid_combinations

# Calculate differences
for prediction in predictions:
    diff = []
    
    # ASH (less is better)
    diff.append(((desired_ash - prediction[0]) / desired_ash) * ash_weightage)

    # VM (less is better)
    diff.append(((desired_VM - prediction[1]) / desired_VM) * vm_weightage)

    # M_40 (higher is better)
    diff.append(((prediction[9] - desired_m40) / desired_m40) * m40_weightage)

    # M_10 (less is better)
    diff.append(((desired_m10 - prediction[10]) / desired_m10) * m10_weightage)

    # CSR (higher is better)
    diff.append(((prediction[12] - desired_csr) / desired_csr) * csn_weightage)

    # CRI (less is better)
    diff.append(((desired_cri - prediction[13]) / desired_cri) * cri_weightage)
    
    # AMS (higher is better)
    #diff.append(((prediction[<value here>] - desired_csr) / desired_csr) * csn_weightage)

    differences.append(diff)

# Calculate total differences and store in an array
total_differences = [sum(diff) for diff in differences]

# Sort the total differences (greatest first, lowest last) and get indices
sorted_indices = np.argsort(total_differences)[::-1]

# Sort predictions based on these indices
sorted_predictions = predictions[sorted_indices]
sorted_blends = all_combinations[sorted_indices]
# Sorting blended coal properties based on the sorted indices
sorted_blended_coal_properties = [blended_coal_properties[i] for i in sorted_indices]



# Get the top three blends

In [44]:
blend_1 = sorted_blends[0]
blend_2 = sorted_blends[1]
blend_3 = sorted_blends[2]

blended_coal_1 = sorted_blended_coal_properties[0]
blended_coal_2 = sorted_blended_coal_properties[1]
blended_coal_3 = sorted_blended_coal_properties[2]


blend_1_properties = sorted_predictions[0]
blend_2_properties = sorted_predictions[1]
blend_3_properties = sorted_predictions[2]


# Printing the blend values and their corresponding properties
print("Blend 1:")
print("Blend Values:", blend_1)
print("Properties:", blend_1_properties, "\n")

print("Blend 2:")
print("Blend Values:", blend_2)
print("Properties:", blend_2_properties, "\n")

print("Blend 3:")
print("Blend Values:", blend_3)
print("Properties:", blend_3_properties)

Blend 1:
Blend Values: [45 25 10 10 10  0  0  0  0  0  0  0  0]
Properties: [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598] 

Blend 2:
Blend Values: [26 36 10 12 13  0  3  0  0  0  0  0  0]
Properties: [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598] 

Blend 3:
Blend Values: [26 36 10 11 12  5  0  0  0  0  0  0  0]
Properties: [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598]


# Input Cost 

In [45]:
coal_costs = [0] * 14  # Initializing an array with 13 elements

# Example input: Replace these values with the actual costs
coal_costs = [12000, 5200, 20160, 20160, 20160, 20160, 17000, 17000, 13440, 14200, 13440, 13440, 15000,9240]


# Calculate which blend has lowest cost 

In [46]:
# Calculating the total cost for each prediction using the sorted blend values and coal costs
total_costs = [sum(blend[i] * coal_costs[i] / 100 for i in range(13)) for blend in sorted_blends]

total_costs

[12748.0,
 12558.0,
 12652.8,
 12526.400000000001,
 12558.000000000002,
 12589.600000000002,
 12621.2,
 12652.800000000001,
 12558.0,
 12589.6,
 12621.2,
 12652.8,
 12589.6,
 12621.2,
 12652.800000000001,
 12621.2,
 12652.800000000001,
 12652.8,
 12526.400000000001,
 12558.0,
 12589.6,
 12621.2,
 12526.400000000001,
 12558.000000000002,
 12589.6,
 12621.2,
 12652.800000000001,
 12526.400000000001,
 12558.000000000002,
 12589.600000000002,
 12621.2,
 12621.199999999999,
 12589.599999999999,
 12558.0,
 12621.2,
 12621.2,
 12526.4,
 12558.0,
 12589.599999999999,
 12621.199999999999,
 12652.8,
 12526.4,
 12558.0,
 12589.6,
 12621.199999999999,
 12652.8,
 12558.0,
 12589.6,
 12652.8,
 12526.4,
 12589.6,
 12621.2,
 12652.800000000001,
 12621.2,
 12652.800000000001,
 12652.8,
 12526.4,
 12558.0,
 12589.6,
 12526.400000000001,
 12558.0,
 12589.6,
 12621.2,
 12652.800000000001,
 12589.6,
 12526.4,
 12621.2,
 12558.0,
 12589.6,
 12621.2,
 12652.8,
 12589.599999999999,
 12621.199999999999,
 12652

In [47]:
sorted_indices_by_cost = np.argsort(total_costs)

# Creating lists for sorted blends and predictions based on cost
sorted_blend_cost = sorted_blends[sorted_indices_by_cost]
sorted_prediction_cost = sorted_predictions[sorted_indices_by_cost]
sorted_total_cost = np.array(total_costs)[sorted_indices_by_cost]

sorted_blended_coal_properties_cost = [sorted_blended_coal_properties[i] for i in sorted_indices_by_cost]

In [48]:
# Normalizing total costs and total differences
normalized_costs = (total_costs - np.min(total_costs)) / (np.max(total_costs) - np.min(total_costs))
normalized_differences = (total_differences - np.min(total_differences)) / (np.max(total_differences) - np.min(total_differences))

# Define weights (adjust these as needed)
cost_weight = 1  # Weight for cost (can be adjusted)
performance_weight = 1  # Weight for performance (can be adjusted)

# Calculate combined scores
combined_scores = (cost_weight * normalized_costs) + (performance_weight * normalized_differences)

# Find the index of the best combined score
best_combined_index = np.argmin(combined_scores)

# Extract the best blend and its corresponding properties
best_blend_combined = sorted_blends[best_combined_index]
best_properties_combined = sorted_predictions[best_combined_index]
best_cost_combined = sorted_total_cost[best_combined_index] 
best_blended_coal_combined = sorted_blended_coal_properties_cost[best_combined_index]

# Print the results
print("Best Blend (Balanced):", best_blend_combined)
print("Properties of Best Blend (Balanced):", best_properties_combined)
print("Cost of Best Blend (Balanced):", best_cost_combined)

Best Blend (Balanced): [45 25 10 10 10  0  0  0  0  0  0  0  0]
Properties of Best Blend (Balanced): [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598]
Cost of Best Blend (Balanced): 11388.0


/var/folders/yx/s6pl3jdx2xj7qkbwp9djq2r00000gp/T/ipykernel_11428/1198232165.py:3: RuntimeWarning: invalid value encountered in true_divide
  normalized_differences = (total_differences - np.min(total_differences)) / (np.max(total_differences) - np.min(total_differences))


In [49]:
# Function to calculate the total cost for a blend
def calculate_cost(blend, coal_costs):
    return sum(blend[i] * coal_costs[i] / 100 for i in range(min(len(blend), len(coal_costs))))

# Blend definitions
blend_1 = sorted_blends[0]
blend_2 = sorted_blend_cost[0]
blend_3 = sorted_blends[best_combined_index]

#Blended coal properties
blended_coal_1 = sorted_blended_coal_properties[0]
blended_coal_2 = sorted_blended_coal_properties_cost [0]
blended_coal_3 = sorted_blended_coal_properties_cost[best_combined_index]


# Properties definitions
blend_1_properties = sorted_predictions[0]
blend_2_properties = sorted_prediction_cost[0]
blend_3_properties = sorted_predictions[best_combined_index]

# Calculating costs on the spot
blend_1_cost = calculate_cost(blend_1, coal_costs)
blend_2_cost = sorted_total_cost[0]
blend_3_cost = calculate_cost(blend_3, coal_costs)

# Printing the blend values, properties, and calculated cost
print("Blend 1 (First in Sorted Blends):")
print("Blend Values:", blend_1)
print("Properties:", blend_1_properties)
print("Cost:", blend_1_cost, "\n")

print("Blend 2 (Lowest Cost):")
print("Blend Values:", blend_2)
print("Properties:", blend_2_properties)
print("Cost:", blend_2_cost, "\n")

print("Blend 3 (Best Combined):")
print("Blend Values:", blend_3)
print("Properties:", blend_3_properties)
print("Cost:", blend_3_cost, "\n")


Blend 1 (First in Sorted Blends):
Blend Values: [45 25 10 10 10  0  0  0  0  0  0  0  0]
Properties: [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598]
Cost: 12748.0 

Blend 2 (Lowest Cost):
Blend Values: [25 45 10 10 10  0  0  0  0  0  0  0  0]
Properties: [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598]
Cost: 11388.0 

Blend 3 (Best Combined):
Blend Values: [45 25 10 10 10  0  0  0  0  0  0  0  0]
Properties: [15.48312069  0.94561219  4.04161287  0.82918282  1.52002634 19.05713319
 33.58277437 24.00576627  6.45681289 92.67922727  6.13754018  4.22143969
 68.46619464 23.35850598]
Cost: 12748.0 

